name: push

on: [push]

jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Get GIT Version infromation
        id: version
        run: |
            GIT_HASH=$(git rev-parse HEAD)
            GIT_VERSION=$(git describe --tags --always --match 'v*')
            GIT_VERSION_MAJOR=$(echo $GIT_VERSION | cut -d. -f1)
            GIT_VERSION_MAJOR_MINOR=$(echo $GIT_VERSION | cut -d. -f1,2)

            echo "hash=${GIT_HASH}" >> $GITHUB_OUTPUT
            echo "version=${GIT_VERSION}" >> $GITHUB_OUTPUT
            echo "version_major=${GIT_VERSION_MAJOR}" >> $GITHUB_OUTPUT
            echo "version_major_minor=${GIT_VERSION_MAJOR_MINOR}" >> $GITHUB_OUTPUT
      - name: Setup docker tags
        id: tags
        uses:  actions/github-script@v6
        with: 
            result-encoding: string
            script: 
              const tags = [];
              tags.push('ghcr.io/${{ github.repository }}:latest');
              tags.push('ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}');

              const isMaster = context.ref === 'refs/heads/master';
              const isRelease = context.payload.head_commit.message.startsWith('release:');

              console.log({isMaster, isRelease})
              return tags.join(', ')
