name: CI
on: [push]

jobs:
  reusable-workflow:
    uses: linz/action-typescript/.github/workflows/workflow.yml@workflow
    # - with:
    #     registry-url: "https://npm.pkg.github.com"
    #     package-manager: "yarn"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        uses: linz/action-typescript@workflow
        with:
          registry-url: "https://npm.pkg.github.com"
          package-manager: "yarn"
