name: CI
on: [push]

jobs:
  reusable-workflow:
    name: 'Reusable workflow Test'
    uses: linz/action-typescript/.github/workflows/workflow.yml@workflow
    with:
      registry-url: "https://npm.pkg.github.com"
      package-manager: "yarn"

  composite-action:
    runs-on: ubuntu-latest
    steps: 
      - name: Build and test
        uses: linz/action-typescript@v1
        with:
          registry-url: "https://npm.pkg.github.com"
          package-manager: "yarn"
