name: push

on: 
  push:

jobs:
  reusable-workflow:
    uses: linz/action-typescript/.github/workflows/main.yml@v1
    with:
      registry-url: "https://npm.pkg.github.com"
      package-manager: "pnpm"

  composite-action:
    runs-on: ubuntu-latest
    steps: 
      - name: Build and test
        uses: linz/action-typescript@v1
        with:
          registry-url: "https://npm.pkg.github.com"
          package-manager: "pnpm"
