name: push

on: [push]

jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Setup docker tags
        id: tags
        uses:  actions/github-script@v6
        with: 
            result-encoding: string
            script: 
              const tags = [];
              tags.push('ghcr.io/${{ github.repository }}:latest');
              tags.push('ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}');
              console.log(JSON.stringify(context, null, 2));

              return tags.join(', ')
