name: CI
on: [push]

jobs:
  reusable-workflow:
    name: 'Reusable workflow Test'
    uses: linz/action-typescript/.github/workflows/workflow.yml@workflow
    with:
      registry-url: "https://npm.pkg.github.com"
      package-manager: "yarn"
    steps:
      - name: 'Test run'
        run: ls -alh