name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    uses: linz/action-typescript/.github/workflows/workflow@workflow
    with:
      registry-url: "https://npm.pkg.github.com"

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: linz/action-typescript/.github/workflows/workflow@workflow
  #       with:
  #         package-manager: 'yarn'
  #     - run: |
  #         ls -alh
