name: CI
on: [push]

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: linz/action-typescript/.github/workflows/workflow@workflow
        with:
          package-manager: 'yarn'

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: linz/action-typescript/.github/workflows/workflow@workflow
  #       with:
  #         package-manager: 'yarn'
  #     - run: |
  #         ls -alh
