name: push

on: [push]

jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Get GIT Version infromation
        id: version
        run: |
            GIT_VERSION=$(git describe --tags --always --match 'v*')
            GIT_VERSION_MAJOR=$(echo $GIT_VERSION | cut -d. -f1)
            GIT_VERSION_MAJOR_MINOR=$(echo $GIT_VERSION | cut -d. -f1,2)

            echo "version=${GIT_VERSION}" >> $GITHUB_OUTPUT
            echo "version_major=${GIT_VERSION_MAJOR}" >> $GITHUB_OUTPUT
            echo "version_major_minor=${GIT_VERSION_MAJOR_MINOR}" >> $GITHUB_OUTPUT
      - name: Setup docker tags
        id: tags
        uses:  actions/github-script@v6
        with: 
            result-encoding: string
            script: 
              const tags = [];
              const isMaster = context.ref === 'refs/heads/master';
              const isRelease = context.payload.head_commit.message.startsWith('release:');
              
              console.log({isMaster, isRelease});
              return tags.join(', ')

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build and push - Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.tags.outputs.result }}
          args:
            GIT_VERSION=${{ steps.version.outputs.version }}
            GIT_HASH=${{ github.sha }}
          push: false