name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        uses: linz/action-typescript@workflow
        with:
          registry-url: "https://npm.pkg.github.com"
          package-manager: "pnpm"
