on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releases_created }}
    steps:
      - name: Build and test
        uses: linz/action-typescript@v3
        with:
          registry-url: "https://npm.pkg.github.com"

      - name: Publish to NPM
        run: npx lerna publish from-package --no-push --no-private --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
