name: Release
on:
  push:
    branches:
      - master

jobs:
  release_please:
    name: Release Please Pull Request
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name}}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          token: ${{ secrets.GITHUB_TOKEN }}

  build_artifacts:
    name: Build artifacts
    permissions:
      contents: read
      id-token: write

    needs: release_please
    if: ${{ needs.release_please.outputs.release_created }}
    strategy:
        fail-fast: false
        matrix:
          include:
            - target: x86_64-linux
              os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4

      - name: Build Binary
        run: |
            go build -o ${{ matrix.target }}/argo-expr

      - name: Pacakge release
        run: |
            cd ${{ matrix.target }}/
            cp ../README.md .
            cp ../CHANGELOG.md .
            cp ../LICENSE .
            tar czvf ../argo-expr-${{ matrix.target }}.tar.gz *
            cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: argo-expr-${{ matrix.target }}.tar.gz
          path: argo-expr-${{ matrix.target }}.tar.gz

  upload_artifacts:
    name: Add Build Artifacts to Release
    needs: [release_please, build_artifacts]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Adding assets require permissions
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create checksums
        run: for file in argo-expr-*/argo-expr-*; do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done

      - name: Add artifacts To release
        run: |
          gh release upload ${{ needs.release_please.outputs.tag_name }} argo-expr-*/argo-expr* --repo=${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
