name: 'Version'
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
        default: 'patch'
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Begin CI...
      uses: actions/checkout@v2
    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - run: yarn
    - run: npm version ${{ github.event.inputs.version }}
